config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'

  post 'entries/:entry_id/comments' => 'entries#add_comment'

  #Must come before resources :images below
  get 'images/banner' => 'images#banner'
  get 'category/:name' => 'categories#show'
  get 'feed' => 'blog#feed', only: [:show], defaults: { format: 'rss' }

  resources :subscriptions, only: [:create] do
    member do
      get :confirm_email
      get :not_found
      get :success
      get :unsubscribe
      get :unsubscribe_success
      get :unsubscribe_failure
    end
  end
  resources :entries, only: [:show]
  resources :images, only: [:show]
  resource :sitemap, only: [:show], defaults: { format: 'json' }

  ADMIN_PROTOCOL = (Rails.env.production? ? "https" : "http")

  namespace :admin do
    root to: 'admin#index', protocol: ADMIN_PROTOCOL
    resource :authentications, only: [:create, :new, :destroy], protocol: ADMIN_PROTOCOL
    resource :settings, only: [:show, :update], protocol: ADMIN_PROTOCOL
    resource :subscriptions, only: [:show], protocol: ADMIN_PROTOCOL
    resources :entries, only: [:create, :new, :edit, :update, :show, :destroy, :index], protocol: ADMIN_PROTOCOL do
      resources :history, only: [:index, :show], protocol: ADMIN_PROTOCOL

      post 'history/:id/restore' => 'history#restore', protocol: ADMIN_PROTOCOL
    end
    resources :categories, only: [:create, :new, :edit, :update, :show, :index], protocol: ADMIN_PROTOCOL
    resources :images, only: [:create, :new, :show, :destroy, :index], protocol: ADMIN_PROTOCOL
    resources :users, only: [:create, :new, :edit, :update, :show, :index], protocol: ADMIN_PROTOCOL
    resources :test_email, only: [:create], protocol: ADMIN_PROTOCOL
    resources :tracker, only: [:index], protocol: ADMIN_PROTOCOL

    post 'entries/:id/publish' => 'entries#publish', protocol: ADMIN_PROTOCOL
    post 'entries/:id/unpublish' => 'entries#unpublish', protocol: ADMIN_PROTOCOL

    post 'images/banner' => 'images#set_banner', protocol: ADMIN_PROTOCOL
    post 'images/:id/publish' => 'images#publish', protocol: ADMIN_PROTOCOL
    post 'images/:id/unpublish' => 'images#unpublish', protocol: ADMIN_PROTOCOL

    delete 'comments/:id' => 'comments#delete', protocol: ADMIN_PROTOCOL
    put 'comments/:id/approve' => 'comments#approve', protocol: ADMIN_PROTOCOL
    put 'comments/:id/unapprove' => 'comments#unapprove', protocol: ADMIN_PROTOCOL

  end
end

app/controllers/admin/history_controller.rb
class Admin::HistoryController < Admin::AdminAreaController
  def index
    @entry = Entry.find(params[:entry_id])
    @historical_entries = @entry.historical_entries.order(:created_at)
  end

  def show
    @entry = Entry.find(params[:entry_id])
    @historical_entry = @entry.historical_entries.where(id: params[:id]).first

    raise ActionController::RoutingError.new('Not Found') if @historical_entry.nil?

    renderer = Redcarpet::Render::HTML.new(escape_html: true)
    @markdown = Redcarpet::Markdown.new(renderer, extensions = {})
    @settings = Setting.all.first
  end

  def restore
    @entry = Entry.find(params[:entry_id])
    @historical_entry = @entry.historical_entries.where(id: params[:id]).first

    raise ActionController::RoutingError.new('Not Found') if @historical_entry.nil?
    
    Entry.transaction do
      new_historical_entry = HistoricalEntry.from_entry(@entry)
      @historical_entry.restore_to_entry(@entry)

      new_historical_entry.save
      @entry.save
    end
    redirect_to admin_entries_path
  end
end

app/views/admin/history/_historical_entry_line_item.html.erb
<tr>
  <td><%= historical_entry_line_item.title %></td>
  <td><%= format_datetime(historical_entry_line_item.created_at) %></td>
  <td>
    <%= link_to(image_tag('ic_find_in_page_black_24dp.png', title: "View Historical Entry"), admin_entry_history_path(entry, historical_entry_line_item)) %>
    <%= link_to(
          image_tag('ic_restore_black_24dp.png', title: "Restore this Revision"),
          "/admin/entries/#{entry.id}/history/#{historical_entry_line_item.id}/restore",
          method: 'post',
          data: { confirm: 'Are you sure you want to restore this revision?' }) %>
  </td>
</tr>

app/views/admin/history/index.html.erb
<div class="row">
  <h2>Historical Entries for '<em><%= @entry.title %>'</em></h2>
  <h3>Last Updated: <em><%= format_datetime(@entry.updated_at) %></em></h3>
</div>
<div class="row">
  <table>
  <tr>
    <th>Title</th><th>Created Date</th><th>Actions</th>
  </tr>
  <%= render partial: "historical_entry_line_item", collection: @historical_entries, locals: { entry: @entry } %>
  </table>
</div>
<div class="row">
  <%= link_to('Back', admin_entries_path, class: 'button round') %>
</div>

app/views/admin/history/show.html.erb
<div class="row">
  <h2>Historical Entries for '<em><%= @entry.title %>'</em></h2>
  <h3>Revision Date: <em><%= format_datetime(@historical_entry.created_at) %></em></h3>
</div>
<div class="row">
    <div>
      <p><strong>Revision Title:</strong> <%= @historical_entry.title %></p>
      <p><strong>Category:</strong> <%= @historical_entry.category.name %></p>
      <hr />
      <%= @markdown.render(@historical_entry.entry).html_safe %>
    </div>
</div>
<div class="row">
  <div class="small-6 small-centered columns">
    <%= link_to(
          'Restore Revision',
          "/admin/entries/#{@entry.id}/history/#{@historical_entry.id}/restore",
          method: 'POST',
          class: 'button round success',
          data: { confirm: 'Are you sure you want to restore this revision?' }
        ) 
    %>
    <%= link_to('Back', admin_entry_history_index_path(@entry), class: 'button round') %>
  </div>
</div>