config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'

  post 'entries/:entry_id/comments' => 'entries#add_comment'

  #Must come before resources :images below
  get 'images/banner' => 'images#banner'
  get 'category/:name' => 'categories#show'
  get 'feed' => 'blog#feed', only: [:show], defaults: { format: 'rss' }

  resources :subscriptions, only: [:create] do
    member do
      get :confirm_email
      get :not_found
      get :success
      get :unsubscribe
      get :unsubscribe_success
      get :unsubscribe_failure
    end
  end
  resources :entries, only: [:show]
  resources :images, only: [:show]
  resource :sitemap, only: [:show], defaults: { format: 'json' }

  ADMIN_PROTOCOL = (Rails.env.production? ? "https" : "http")

  namespace :admin do
    root to: 'admin#index', protocol: ADMIN_PROTOCOL
    resource :authentications, only: [:create, :new, :destroy], protocol: ADMIN_PROTOCOL
    resource :settings, only: [:show, :update], protocol: ADMIN_PROTOCOL
    resource :subscriptions, only: [:show], protocol: ADMIN_PROTOCOL
    resources :entries, only: [:create, :new, :edit, :update, :show, :destroy, :index], protocol: ADMIN_PROTOCOL do
      resources :history, only: [:index, :show], protocol: ADMIN_PROTOCOL

      post 'history/:id/restore' => 'history#restore', protocol: ADMIN_PROTOCOL
    end
    resources :categories, only: [:create, :new, :edit, :update, :show, :index], protocol: ADMIN_PROTOCOL
    resources :images, only: [:create, :new, :show, :destroy, :index], protocol: ADMIN_PROTOCOL
    resources :users, only: [:create, :new, :edit, :update, :show, :index], protocol: ADMIN_PROTOCOL
    resources :test_email, only: [:create], protocol: ADMIN_PROTOCOL
    resources :tracker, only: [:index], protocol: ADMIN_PROTOCOL

    post 'entries/:id/publish' => 'entries#publish', protocol: ADMIN_PROTOCOL
    post 'entries/:id/unpublish' => 'entries#unpublish', protocol: ADMIN_PROTOCOL

    post 'images/banner' => 'images#set_banner', protocol: ADMIN_PROTOCOL
    post 'images/:id/publish' => 'images#publish', protocol: ADMIN_PROTOCOL
    post 'images/:id/unpublish' => 'images#unpublish', protocol: ADMIN_PROTOCOL

    delete 'comments/:id' => 'comments#delete', protocol: ADMIN_PROTOCOL
    put 'comments/:id/approve' => 'comments#approve', protocol: ADMIN_PROTOCOL
    put 'comments/:id/unapprove' => 'comments#unapprove', protocol: ADMIN_PROTOCOL

  end
end

app/models/authentication.rb
require 'bcrypt'

class LoginValidator < ActiveModel::Validator
    include BCrypt
    
    def validate(record)
        user = User.find_by_email(record.email)
        if user.nil?
            record.errors[:email] << 'Email could not be found or password was not correct!'
        else
            if Password.new(user.password_hash) != record.password
                record.errors[:password] << 'Email could not be found or password was not corect!'
            end
        end
    end
end

class Authentication
    include ActiveModel::Validations      
    include ActiveModel::Conversion       
    include BCrypt
    extend ActiveModel::Naming            
                                                
    validates :email, presence: { message: "Email is required" }, email: { message: "Must be a validly formatted email address" }
    validates :password, presence: { message: "Password is required" }
    validates_with LoginValidator
    
    def initialize(options = {})
        self.email = options[:email]
        self.password = options[:password]
    end
    
    def self.create(options = {})
        authentication = Authentication.new(options)
        
        if authentication.valid?
            authentication.user = User.where(email: authentication.email).first
        end
        
        return authentication
    end
    
    attr_accessor :email
    attr_accessor :password
    attr_accessor :user

end

app/controllers/admin/authentications_controller.rb
class Admin::AuthenticationsController < Admin::AdminAreaController
  skip_before_action :check_authentication, only: [:new, :create]

  def new
    @authentication = Authentication.new
  end

  def create
    @authentication = Authentication.create(
      email: params[:email],
      password: params[:password]
    )

    if @authentication.errors.size > 0
      render :new
    else
      session[:current_user_id] = @authentication.user.id
      @current_user = @authentication.user
      @current_user.update_attribute(:last_login, DateTime.now)
      @current_user.save(validate: false) 

      redirect_to admin_root_path
    end
  end

  def destroy
    if session[:current_user_id]
      session.delete(:current_user_id)
      @current_user = nil
    end
    redirect_to root_path
  end
end

app/views/admin/authentications/new.html.erb
<div class="row">
    <div class="medium-6 medium-centered columns">
        <h3>Miniblog Login</h3>
    </div>
</div>

<%= form_tag(admin_authentications_path, method: :post) do %>
    <div class="row">
        <div class="medium-6 medium-centered columns <%= @authentication.errors[:email].any? ? "error" : ""  %>">
            <%= label_tag(:email, "Email:") %>
            <%= text_field_tag(:email, @authentication.email) %>
            <% if @authentication.errors[:email].any? %>
                <small class="error"><%= @authentication.errors[:email].join(', ') %></small>
            <% end %>
        </div>
    </div>
    
    <div class="row">
        <div class="medium-6 medium-centered columns <%= @authentication.errors[:password].any? ? "error" : "" %>">
            <%= label_tag(:password, "Password:") %>
            <%= password_field_tag(:password) %>
            
            <% if @authentication.errors[:password].any? %>
                <small class="error"><%= @authentication.errors[:password].join(', ') %></small>
            <% end %>
        </div>
    </div>
    
    <div class="row">
        <div class="medium-6 medium-centered columns">
            <%= submit_tag("Login", class: "button small round") %>
        </div>
    </div>
<% end %>