config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'

  post 'entries/:entry_id/comments' => 'entries#add_comment'

  #Must come before resources :images below
  get 'images/banner' => 'images#banner'
  get 'category/:name' => 'categories#show'
  get 'feed' => 'blog#feed', only: [:show], defaults: { format: 'rss' }

  resources :subscriptions, only: [:create] do
    member do
      get :confirm_email
      get :not_found
      get :success
      get :unsubscribe
      get :unsubscribe_success
      get :unsubscribe_failure
    end
  end
  resources :entries, only: [:show]
  resources :images, only: [:show]
  resource :sitemap, only: [:show], defaults: { format: 'json' }

  ADMIN_PROTOCOL = (Rails.env.production? ? "https" : "http")

  namespace :admin do
    root to: 'admin#index', protocol: ADMIN_PROTOCOL
    resource :authentications, only: [:create, :new, :destroy], protocol: ADMIN_PROTOCOL
    resource :settings, only: [:show, :update], protocol: ADMIN_PROTOCOL
    resource :subscriptions, only: [:show], protocol: ADMIN_PROTOCOL
    resources :entries, only: [:create, :new, :edit, :update, :show, :destroy, :index], protocol: ADMIN_PROTOCOL do
      resources :history, only: [:index, :show], protocol: ADMIN_PROTOCOL

      post 'history/:id/restore' => 'history#restore', protocol: ADMIN_PROTOCOL
    end
    resources :categories, only: [:create, :new, :edit, :update, :show, :index], protocol: ADMIN_PROTOCOL
    resources :images, only: [:create, :new, :show, :destroy, :index], protocol: ADMIN_PROTOCOL
    resources :users, only: [:create, :new, :edit, :update, :show, :index], protocol: ADMIN_PROTOCOL
    resources :test_email, only: [:create], protocol: ADMIN_PROTOCOL
    resources :tracker, only: [:index], protocol: ADMIN_PROTOCOL

    post 'entries/:id/publish' => 'entries#publish', protocol: ADMIN_PROTOCOL
    post 'entries/:id/unpublish' => 'entries#unpublish', protocol: ADMIN_PROTOCOL

    post 'images/banner' => 'images#set_banner', protocol: ADMIN_PROTOCOL
    post 'images/:id/publish' => 'images#publish', protocol: ADMIN_PROTOCOL
    post 'images/:id/unpublish' => 'images#unpublish', protocol: ADMIN_PROTOCOL

    delete 'comments/:id' => 'comments#delete', protocol: ADMIN_PROTOCOL
    put 'comments/:id/approve' => 'comments#approve', protocol: ADMIN_PROTOCOL
    put 'comments/:id/unapprove' => 'comments#unapprove', protocol: ADMIN_PROTOCOL

  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 50 }

  def self.query
    Image
  end

  def self.find_published_by_token(url_token) 
    Image
      .where(url_token: url_token, is_published: true, is_deleted: false)
      .first
  end

  def self.published_images_ordered_by_title
    Image
      .where(is_published: true, is_deleted: false)
      .order(:title)
  end

  def self.published_images_ordered_by_pub_date
    Image
      .where(is_published: true, is_deleted: false)
      .order(published_at: :desc)
  end

  def self.published_images
    Image
      .where(is_published: true, is_deleted: false)
  end

  def self.available_images
    Image
      .where(is_deleted: false)
  end

  def self.available_images_ordered_by_crated_date
    Image
      .where(is_deleted: false)
      .order(:created_at)
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::AdminAreaController
  MAX_FILE_SIZE = 20_000_000
  CONTENT_TYPE_WHITELIST = ['image/jpeg', 'image/gif', 'image/png'].freeze

  def index
    @images = Image.available_images

    respond_to do |format|
      format.html
      format.json { render :json => Image.published_images }
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.is_deleted = true
    @image.deleted_at = DateTime.now
    @image.save

    redirect_to admin_images_path
  end

  def publish
    @image = Image.find(params[:id])
    @image.is_published = true
    @image.published_at = DateTime.now
    @image.save

    redirect_to admin_images_path
  end

  def unpublish
    @image = Image.find(params[:id])
    @image.is_published = false
    @image.published_at = nil
    @image.save

    redirect_to admin_images_path
  end

  def new
    @image = Image.new
  end

  def create
    uploaded_io = params[:image][:upload_file]
   
    image_uuid = SecureRandom.uuid
  
    Image.transaction do

      @image = Image.new
      if uploaded_io.nil?
        @image.errors.add(:upload_file, 'File must be selected to upload')
      elsif uploaded_io.size > MAX_FILE_SIZE
        @image.errors.add(:upload_file, 'File must be less than 20 MB')
      elsif CONTENT_TYPE_WHITELIST.exclude?(uploaded_io.content_type)
        @image.errors.add(:upload_file, 'File must be a jpeg, png or gif')
      else
        @image.title = params[:image][:title] 
        @image.url_token = image_uuid
        @image.file_name = uploaded_io.original_filename
        @image.content_type = uploaded_io.content_type
        @image.save 
      end
      
      if @image.errors.any?
        render :new   
      else
        filename = Rails.root.join('public', 'uploads', image_uuid)

        File.open(filename, 'wb') do |file|
          file.write(uploaded_io.read)
        end 

        redirect_to admin_images_path
      end
    end
  end

  private
  def entry_params
    params
      .require(:image)
      .permit(:title, :upload_file)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  skip_before_action :populate_default_models 
  skip_after_action :track_request

  def show
    image = Image.find_published_by_token(params[:id]) 

    ActionController::RoutingError.new('Not Found') unless image.present?

    send_image(image.url_token, image.content_type)
  end

  def banner
    settings = Setting.get
    banner_image = settings.banner_image

    response.headers["Expires"] = 1.hour.from_now.httpdate
    if banner_image.present? && banner_image.is_published?
      send_image(banner_image.url_token, banner_image.content_type)
    else
      head :no_content
    end
  end

  def index
    images = Image.published_images_ordered_by_pub_date
  end
 
  private

  def send_image(token, content_type)
    file_name_on_disk = Rails.root.join('public', 'uploads', token)
    send_data(open(file_name_on_disk, "rb") { |f| f.read }, type: content_type, disposition: 'inline')
  end
end

app/views/admin/images/_image_table_row.erb
<tr>
  <td>
    <%= image_table_row.title %>
  </td>
  <td>
    <%= image_table_row.published_at.presence || 'Unpublished'  %>
  </td>
  <td>
    <%= image_table_row.created_at %>
  </td>
  <td>
    <% if image_table_row.is_published? %>
      <%= link_to(
            image_tag('ic_visibility_off_black_24dp.png', title: "Unpublish Image"), 
            "#{admin_image_path(image_table_row)}/unpublish", 
            method: 'post',
            data: { confirm: 'Are you sure you want to unpublish this image?' } 
            ) %>
    <% else %>
      <%= link_to(image_tag('ic_visibility_black_24dp.png', title: "Publish Image"), "#{admin_image_path(image_table_row)}/publish", method: 'post') %>
    <% end %>
    <%= link_to(
          image_tag('ic_delete_black_24dp.png', title: "Delete Image"),
          admin_image_path(image_table_row),
          method: 'delete',
          data: { confirm: 'Are you sure you want to delete this image?' }) %>
  </td>
</tr>

app/views/admin/images/index.html.erb
<div class="row">
  <h2>Images</h2>
</div>
<div class="row">
  <div class="small-12 column">
  <%= link_to(image_tag('ic_note_add_black_24dp.png') + 'Update new image', new_admin_image_path) %>
  </div>
</div>
<div class="row">
  <table>
    <tr>
      <th>Title</th><th>Published At</th><th>Created</th><th>Actions</th>
    </tr>
    <%= render partial: "image_table_row", collection: @images %>
  </table>
</div>

app/views/admin/images/new.html.erb
<div class="row">
  <div class="medium-6 columns medium-centered">
    <h2>Upload New Image</h2>
  </div>
</div>
<div class="row">
  <%= form_for [:admin, @image] do |f| %>
    <div class="row">                                                   
      <div class="medium-6 columns">                          
        <div class="<%= @image.errors[:title].any? ? "error" : "" %>">
          <%= f.label(:title, "Title:") %>                  
          <%= f.text_field(:title) %>                            
          <% if @image.errors[:title].any? %>                   
            <small class="error"><%= @image.errors[:title].join(', ') %></small>
          <% end %>                                                   
        </div>              
      </div>
    </div>
    <div class="row">
      <div class="medium-6 columns">
        <div class="<%= @image.errors[:upload_file].any? ? "error" : "" %>">
          <%= f.label(:upload_file, "Select a file to upload:") %>                  
          <%= f.file_field(:upload_file) %>                            
          <% if @image.errors[:upload_file].any? %>                   
            <small class="error"><%= @image.errors[:upload_file].join(', ') %></small>
          <% end %>                                                   
        </div>              
      </div>
    </div>
    <div class="row">
      <div class="medium-6 columns">                          
        <%= f.submit(class: "button round success") %>                       
        <%= link_to("Cancel", admin_entries_path, class: "button round") %>
      </div> 
    </div>
  <% end %>
</div>