config/routes.rb
Rails.application.routes.draw do
  root 'blog#index'

  post 'entries/:entry_id/comments' => 'entries#add_comment'

  #Must come before resources :images below
  get 'images/banner' => 'images#banner'
  get 'category/:name' => 'categories#show'
  get 'feed' => 'blog#feed', only: [:show], defaults: { format: 'rss' }

  resources :subscriptions, only: [:create] do
    member do
      get :confirm_email
      get :not_found
      get :success
      get :unsubscribe
      get :unsubscribe_success
      get :unsubscribe_failure
    end
  end
  resources :entries, only: [:show]
  resources :images, only: [:show]
  resource :sitemap, only: [:show], defaults: { format: 'json' }

  ADMIN_PROTOCOL = (Rails.env.production? ? "https" : "http")

  namespace :admin do
    root to: 'admin#index', protocol: ADMIN_PROTOCOL
    resource :authentications, only: [:create, :new, :destroy], protocol: ADMIN_PROTOCOL
    resource :settings, only: [:show, :update], protocol: ADMIN_PROTOCOL
    resource :subscriptions, only: [:show], protocol: ADMIN_PROTOCOL
    resources :entries, only: [:create, :new, :edit, :update, :show, :destroy, :index], protocol: ADMIN_PROTOCOL do
      resources :history, only: [:index, :show], protocol: ADMIN_PROTOCOL

      post 'history/:id/restore' => 'history#restore', protocol: ADMIN_PROTOCOL
    end
    resources :categories, only: [:create, :new, :edit, :update, :show, :index], protocol: ADMIN_PROTOCOL
    resources :images, only: [:create, :new, :show, :destroy, :index], protocol: ADMIN_PROTOCOL
    resources :users, only: [:create, :new, :edit, :update, :show, :index], protocol: ADMIN_PROTOCOL
    resources :test_email, only: [:create], protocol: ADMIN_PROTOCOL
    resources :tracker, only: [:index], protocol: ADMIN_PROTOCOL

    post 'entries/:id/publish' => 'entries#publish', protocol: ADMIN_PROTOCOL
    post 'entries/:id/unpublish' => 'entries#unpublish', protocol: ADMIN_PROTOCOL

    post 'images/banner' => 'images#set_banner', protocol: ADMIN_PROTOCOL
    post 'images/:id/publish' => 'images#publish', protocol: ADMIN_PROTOCOL
    post 'images/:id/unpublish' => 'images#unpublish', protocol: ADMIN_PROTOCOL

    delete 'comments/:id' => 'comments#delete', protocol: ADMIN_PROTOCOL
    put 'comments/:id/approve' => 'comments#approve', protocol: ADMIN_PROTOCOL
    put 'comments/:id/unapprove' => 'comments#unapprove', protocol: ADMIN_PROTOCOL

  end
end

app/views/admin/admin/index.html.erb
<div class="row">
  <div class="small-6 small-centered columns">
    <h1>Administration Menu</h1>
  </div>
</div>

<div class="row">
  <div class="small-6 small-centered columns">
    <ul class="left">
      <li><%= link_to('Settings', admin_settings_path) %></li>
      <li><%= link_to('Edit Blog Entries', admin_entries_path) %></li>
      <li><%= link_to('Categories', admin_categories_path) %></li>
      <li><%= link_to('Images', admin_images_path) %></li>
      <li><%= link_to('Accounts', admin_users_path) %></li>
      <li><%= link_to('Tracking', admin_tracker_index_path) %></li>
      <li><%= link_to('Subscriptions', admin_subscriptions_path) %></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="small-6 small-centered columns">
    <%= link_to('Send Test Email', admin_test_email_index_path, method: 'POST', class: 'button round success') %>
  </div>
</div>